// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from todolist.djinni

#include "NativeTodoList.hpp"  // my header
#include "Marshal.hpp"
#include "NativeTodo.hpp"
#include "NativeTodoList.hpp"

namespace djinni_generated {

NativeTodoList::NativeTodoList() : ::djinni::JniInterface<::todolist::TodoList, NativeTodoList>("com/mycompany/todolist/TodoList$CppProxy") {}

NativeTodoList::~NativeTodoList() = default;


CJNIEXPORT void JNICALL Java_com_mycompany_todolist_TodoList_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<djinni::CppProxyHandle<::todolist::TodoList>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_mycompany_todolist_TodoList_create(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::todolist::TodoList::create();
        return ::djinni::release(::djinni_generated::NativeTodoList::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_mycompany_todolist_TodoList_00024CppProxy_native_1getTodos(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::CppProxyHandle<::todolist::TodoList>::get(nativeRef);
        auto r = ref->get_todos();
        return ::djinni::release(::djinni::List<::djinni_generated::NativeTodo>::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jint JNICALL Java_com_mycompany_todolist_TodoList_00024CppProxy_native_1addTodo(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_label)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::CppProxyHandle<::todolist::TodoList>::get(nativeRef);
        auto r = ref->add_todo(::djinni::String::toCpp(jniEnv, j_label));
        return ::djinni::release(::djinni::I32::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jboolean JNICALL Java_com_mycompany_todolist_TodoList_00024CppProxy_native_1updateTodoCompleted(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_id, jint j_completed)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::CppProxyHandle<::todolist::TodoList>::get(nativeRef);
        auto r = ref->update_todo_completed(::djinni::I32::toCpp(jniEnv, j_id),
                                            ::djinni::I32::toCpp(jniEnv, j_completed));
        return ::djinni::release(::djinni::Bool::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jboolean JNICALL Java_com_mycompany_todolist_TodoList_00024CppProxy_native_1deleteTodo(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_id)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::CppProxyHandle<::todolist::TodoList>::get(nativeRef);
        auto r = ref->delete_todo(::djinni::I32::toCpp(jniEnv, j_id));
        return ::djinni::release(::djinni::Bool::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
