// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from todolist.djinni

#pragma once

#include "djinni_support.hpp"
#include "todo_list.hpp"

namespace djinni_generated {

class NativeTodoList final : ::djinni::JniInterface<::todolist::TodoList, NativeTodoList> {
public:
    using CppType = std::shared_ptr<::todolist::TodoList>;
    using JniType = jobject;

    using Boxed = NativeTodoList;

    ~NativeTodoList();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeTodoList>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return {jniEnv, ::djinni::JniClass<NativeTodoList>::get()._toJava(jniEnv, c)}; }

private:
    NativeTodoList();
    friend ::djinni::JniClass<NativeTodoList>;
    friend ::djinni::JniInterface<::todolist::TodoList, NativeTodoList>;

};

}  // namespace djinni_generated
