// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from todolist.djinni

#pragma once

#include "djinni_support.hpp"
#include "todo.hpp"

namespace djinni_generated {

class NativeTodo final {
public:
    using CppType = ::todolist::Todo;
    using JniType = jobject;

    using Boxed = NativeTodo;

    ~NativeTodo();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeTodo();
    friend ::djinni::JniClass<NativeTodo>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/mycompany/todolist/Todo") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(ILjava/lang/String;I)V") };
    const jfieldID field_mId { ::djinni::jniGetFieldID(clazz.get(), "mId", "I") };
    const jfieldID field_mLabel { ::djinni::jniGetFieldID(clazz.get(), "mLabel", "Ljava/lang/String;") };
    const jfieldID field_mCompleted { ::djinni::jniGetFieldID(clazz.get(), "mCompleted", "I") };
};

}  // namespace djinni_generated
