// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from todolist.djinni

#import "TDATodo+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto Todo::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.id),
            ::djinni::String::toCpp(obj.label),
            ::djinni::Enum<::todolist::TodoStatus, TDATodoStatus>::toCpp(obj.status)};
}

auto Todo::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[TDATodo alloc] initWithId:(::djinni::I32::fromCpp(cpp.id))
                                 label:(::djinni::String::fromCpp(cpp.label))
                                status:(::djinni::Enum<::todolist::TodoStatus, TDATodoStatus>::fromCpp(cpp.status))];
}

}  // namespace djinni_generated
