// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from todolist.djinni

#import "TDATodoStatus.h"
#import <Foundation/Foundation.h>

@interface TDATodo : NSObject
- (nonnull instancetype)initWithId:(int32_t)id
                             label:(nonnull NSString *)label
                            status:(TDATodoStatus)status;
+ (nonnull instancetype)todoWithId:(int32_t)id
                             label:(nonnull NSString *)label
                            status:(TDATodoStatus)status;

@property (nonatomic, readonly) int32_t id;

@property (nonatomic, readonly, nonnull) NSString * label;

@property (nonatomic, readonly) TDATodoStatus status;

@end
