// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from todolist.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, TDATodoStatus)
{
    TDATodoStatusComplete,
    TDATodoStatusIncomplete,
};
