// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from todolist.djinni

#import "TDATodo.h"
#import "TDATodoStatus.h"
#import <Foundation/Foundation.h>
@class TDATodoList;


@interface TDATodoList : NSObject

+ (nullable TDATodoList *)create;

- (nonnull NSArray *)getTodos;

- (int32_t)addTodo:(nonnull NSString *)label;

- (BOOL)updateTodoStatus:(int32_t)id
                  status:(TDATodoStatus)status;

- (BOOL)deleteTodo:(int32_t)id;

@end
