// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from todolist.djinni

#import "TDATodo.h"
#import <Foundation/Foundation.h>
@class TDATodoList;


@interface TDATodoList : NSObject

+ (nullable TDATodoList *)createWithPath:(nonnull NSString *)path;

- (nonnull NSArray *)getTodos;

- (int32_t)addTodo:(nonnull NSString *)label;

- (BOOL)updateTodoCompleted:(int32_t)id
                  completed:(int32_t)completed;

- (BOOL)deleteTodo:(int32_t)id;

@end
