// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from todolist.djinni

#import "TDATodo.h"


@implementation TDATodo

- (nonnull instancetype)initWithId:(int32_t)id
                             label:(nonnull NSString *)label
                         completed:(int32_t)completed
{
    if (self = [super init]) {
        _id = id;
        _label = [label copy];
        _completed = completed;
    }
    return self;
}

+ (nonnull instancetype)todoWithId:(int32_t)id
                             label:(nonnull NSString *)label
                         completed:(int32_t)completed
{
    return [[self alloc] initWithId:id
                              label:label
                          completed:completed];
}

@end
