// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from todolist.djinni

#pragma once

#include <functional>

namespace todolist {

enum class TodoStatus : int {
    COMPLETE,
    INCOMPLETE,
};

}  // namespace todolist

namespace std {

template <>
struct hash<::todolist::TodoStatus> {
    size_t operator()(::todolist::TodoStatus type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
