// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from todolist.djinni

#pragma once

#include "todo_status.hpp"
#include <cstdint>
#include <string>
#include <utility>

namespace todolist {

struct Todo final {
    int32_t id;
    std::string label;
    TodoStatus status;

    Todo(int32_t id,
         std::string label,
         TodoStatus status)
    : id(std::move(id))
    , label(std::move(label))
    , status(std::move(status))
    {}
};

}  // namespace todolist
